export type Iteratee<T> = keyof T | ((item: T) => string | number | symbol);

export function isPlainObject(value: unknown): value is Record<string, unknown>;
export function isEmpty(value: unknown): boolean;
export function deepClone<T>(value: T): T;
export function debounce<T extends (...args: any[]) => void>(callback: T, delay?: number): (...args: Parameters<T>) => void;
export function throttle<T extends (...args: any[]) => void>(callback: T, delay?: number): (...args: Parameters<T>) => void;
export function sleep(ms?: number): Promise<void>;
export function clamp(value: number, min: number, max: number): number;
export function chunk<T>(list: T[], size?: number): T[][];
export function flatten<T>(list: unknown[], depth?: number): T[];
export function uniqueBy<T>(list: T[], iteratee?: Iteratee<T>): T[];
export function groupBy<T>(list: T[], iteratee: Iteratee<T>): Record<string, T[]>;
export function range(start: number, end?: number, step?: number): number[];
export function sumBy<T>(list: T[], iteratee?: Iteratee<T>): number;
export function sortBy<T>(list: T[], iteratee: Iteratee<T>, order?: 'asc' | 'desc'): T[];
export function getValue<T = unknown>(source: Record<string, any>, path: string | string[], defaultValue?: T): T;
export function setValue<T extends Record<string, any>>(source: T, path: string | string[], value: unknown): T;
export function pick<T extends Record<string, any>, K extends keyof T>(source: T, keys: K[]): Pick<T, K>;
export function omit<T extends Record<string, any>, K extends keyof T>(source: T, keys: K[]): Omit<T, K>;
export function merge<T extends Record<string, any>>(target?: T, ...sources: Record<string, any>[]): T & Record<string, any>;
export function safeJsonParse<T = unknown>(value: string, defaultValue?: T): T;
export function randomString(length?: number): string;
export function capitalize(value: unknown): string;
export function camelCase(value: unknown): string;
export function kebabCase(value: unknown): string;
export function escapeHtml(value: unknown): string;
export function unescapeHtml(value: unknown): string;
export function formatDate(value?: Date | string | number, template?: string): string;
export function stringifyQuery(params?: Record<string, string | number | boolean | null | undefined>): string;
export function parseQuery(query?: string): Record<string, string>;
